### PR TITLE
update julia example to use ClusterManagers.jl

### PR DESCRIPTION
**Pull request by nickeubank**
Apropos our conversations about Julia escaping slurm, here's a working example using the ClusterManager.jl module.

### CODE REVIEW

**Comment by nickeubank** [comment]
(note I THINK this is all inside the slurm group, but since I can't introspect the slurm system, I can't be sure -- if you want to check, you can add `sleep()` calls (in seconds) to the parallel workers so they live longer.

**Comment by nickeubank** [comment]
Hmmm... [don't merge till this is resolved](https://github.com/JuliaParallel/SlurmClusterManager.jl/issues/63)

**Comment by nickeubank** [comment]
OK, think this is good to go. There's still a bug in `ClusterManagers.jl` based around allocations if you specify the number of tasks per node (it doesn't count the managing process, so gets confused if you had asked for 2 tasks per node and try and add 3 workers, since it doesn't think 3 is divisible by 2), but with the update this script should work fine, and hopefully they patch that soon. 

Relatedly: As noted above, I can't introspect slurm, so you may want to run this and make sure that slurm sees these processes (and we don't get more zombies). But pretty sure we're now in good shape.

**Comment by frenchwr** [comment]
Hey @nickeubank, as long as ClusterManagers.jl is launching remote processes with `srun`, then we should be good to go. I don't know of an easy way for us to test whether a process is running within its job's Cgroup (@vanzod do you?) in which case we will just trust that CLusterManagers.jl works as advertised.

**Pull request merged**
